Repository apify/apify-mcp-server, pull requests merged in 2025-05, with the labels that each got.

#104 fix: Actor server default tool loading
  src/actor/server.ts
Labels: t-ai

#106 fix: stdio and streamable http client examples
  src/examples/clientStdio.ts
  src/examples/clientStreamableHttp.ts
Labels: t-ai

#112 fix: Update README with a link to a blog post
  README.md
Labels: t-ai

#103 chore: add tests
  package.json
  src/const.ts
  src/mcp/server.ts
  src/tools/helpers.ts
  tests/README.md
  tests/actor-server-test.ts
  tests/helpers.ts
  tests/integration/actor.server-sse.test.ts
  tests/integration/actor.server-streamable.test.ts
  tests/integration/stdio.test.ts
  tests/integration/suite.ts
  tests/unit/input.test.ts
  tests/unit/mcp.utils.test.ts
  tests/unit/tools.actor.test.ts
  tests/unit/tools.utils.test.ts
  vitest.config.ts
Labels: t-ai, high priority, tested

#113 fix: apify-mcp-server max listeners warning
  src/mcp/server.ts
Labels: t-ai

#114 fix: Use a new API to get Actor default build
  package-lock.json
  package.json
  src/tools/actor.ts
  src/tools/build.ts
Labels: t-ai

#123 fix: Update README.md
  README.md
Labels: t-ai

#117 feat: normal Actor tools cache
  package-lock.json
  package.json
  src/const.ts
  src/mcp/actors.ts
  src/tools/actor.ts
  src/types.ts
  tests/integration/suite.ts
  vitest.config.ts
Labels: t-ai, tested

#128 fix: actor add response
  src/tools/helpers.ts
Labels: t-ai

#130 fix: error and input handling
  src/mcp/server.ts
  src/tools/actor.ts
  src/tools/build.ts
  src/tools/dataset.ts
  src/tools/helpers.ts
  src/tools/key_value_store.ts
  src/tools/run.ts
  tests/integration/actor.server-sse.test.ts
  tests/integration/actor.server-streamable.test.ts
  tests/integration/suite.ts
Labels: t-ai, tested
