Repository apify/apify-mcp-server, pull requests merged in 2025-09, with the labels that each got.

#251 fix: Handle deprecated tool preview
  README.md
  src/tools/build.ts
  src/utils/tools-loader.ts
Labels: t-ai

#265 fix: error when content type is json
  src/tools/actor.ts
Labels: t-ai

#277 fix: duplicate skyfire description when listing tools multiple times
  src/mcp/server.ts
Labels: t-ai

#274 feat: call-actor add support for MCP server Actors
  .gitignore
  src/const.ts
  src/state.ts
  src/tools/actor.ts
  src/utils/actor-response.ts
  src/utils/actor.ts
  tests/integration/suite.ts
Labels: t-ai

#280 chore: manifest.json add privacy policies
  manifest.json
Labels: t-ai

#272 fix: Actorized MCP servers have 30 seconds timeout to connect
  src/errors.ts
  src/mcp/client.ts
  src/mcp/const.ts
  src/mcp/server.ts
  src/tools/actor.ts
  tests/integration/suite.ts
Labels: t-ai

#275 feat/update-tool-desc
  docs/claude-code-tools.json
  package-lock.json
  package.json
  src/const.ts
  src/tools/actor.ts
  src/tools/dataset.ts
  src/tools/dataset_collection.ts
  src/tools/fetch-actor-details.ts
  src/tools/fetch-apify-docs.ts
  src/tools/get-actor-output.ts
  src/tools/get-html-skeleton.ts
  src/tools/helpers.ts
  src/tools/key_value_store.ts
  src/tools/key_value_store_collection.ts
  src/tools/run.ts
  src/tools/run_collection.ts
  src/tools/search-apify-docs.ts
  src/tools/store_collection.ts
  src/tools/utils.ts
Labels: t-ai

#285 fix: Actor card markdown
  README.md
  src/tools/actor.ts
  src/tools/fetch-actor-details.ts
  src/tools/store_collection.ts
  src/utils/actor-card.ts
  src/utils/pricing-info.ts
Labels: t-ai

#281 fix: Change dxt to mcpb in release cicd
  .github/workflows/release.yaml
  CHANGELOG.md
  manifest.json
  package-lock.json
  package.json
Labels: t-ai

#291 feat: Improve README.md
  README.md
Labels: t-ai

#292 fix: Increase ACTOR_ENUM_MAX_LENGTH from 200 to 2000 to ensure that geocode are not removed
  src/const.ts
  src/tools/utils.ts
  tests/unit/tools.utils.test.ts
Labels: t-ai, tested

#293 fix: Provide better output. Fix datasetId in examples
  README.md
  docs/apify-mcp-server.png
  src/tools/actor.ts
  src/tools/dataset.ts
  src/tools/get-actor-output.ts
  src/tools/key_value_store.ts
Labels: t-ai

#296 fix: comment out skyfire input schema modification
  src/mcp/server.ts
Labels: t-ai, beta

#298 fix: revert skyfire schema comment
  src/mcp/server.ts
Labels: t-ai
